version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - ${LOCAL_STACK_PORT-34566}:4566
    environment:
      DEBUG: 1
      SERVICES: dynamodb,s3
      DEFAULT_REGION: ap-northeast-1
    healthcheck:
      test: ["CMD-SHELL", "curl -s localhost:4566/_localstack/init/ready | jq .completed"]
      timeout: 20s
      retries: 10
    volumes:
      - "$PWD/docker/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - 'localstack-data:/tmp/localstack'
  shellspec:
    image: shellspec/shellspec:latest


volumes:
  localstack-data: {}

